import React, { useEffect, useState } from 'react';
import { Check, Plus, RefreshCw, Shield, X } from 'lucide-react';
import api from '../lib/api';

const AdminPage = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ fullName: '', email: '', phone: '', password: '', roleId: 5, roleName: 'SalesPerson' });
  const load = async () => { setLoading(true); try { const response = await api.get('/api/v1/users'); const payload = response.data?.data || response.data || []; const list = Array.isArray(payload) ? payload : payload.items || payload.results || []; setUsers(list.map((user) => ({ ...user, userId: user.userId || user.UserId, fullName: user.fullName || user.FullName, email: user.email || user.Email, role: user.role || user.Role, isActive: user.isActive ?? user.IsActive ?? false }))); setError(''); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const approve = async (userId, approved) => { await api.patch(`/api/v1/users/${userId}/approval`, { approved }); await load(); };
  const createUser = async (event) => { event.preventDefault(); try { await api.post('/api/v1/users', { ...form, role: { roleId: Number(form.roleId), name: form.roleName } }); setShowCreate(false); setForm({ fullName: '', email: '', phone: '', password: '', roleId: 5, roleName: 'SalesPerson' }); await load(); } catch (requestError) { setError(requestError.message); } };
  const pending = users.filter((user) => !user.isActive);
  return <div className="admin-page"><div className="page-heading"><div><p className="eyebrow">Administration / governance</p><h2>People & access</h2><p className="muted">Approve managers, protect access, and keep responsibility clear.</p></div><div className="workspace-actions"><button className="secondary-button" onClick={load}><RefreshCw size={16} />Refresh</button><button className="primary-button" onClick={() => setShowCreate(true)}><Plus size={16} />Create user</button></div></div>{error && <div className="notice error">{error}</div>}<section className="admin-banner"><Shield size={26} /><div><strong>Admin control room</strong><span>Only administrators can approve manager requests or manage users.</span></div><b>{pending.length} pending</b></section>{loading ? <div className="loading-state">Loading access requests...</div> : <div className="table-wrap"><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map((user) => <tr key={user.userId}><td><strong>{user.fullName}</strong><small>{user.email}</small></td><td>{user.role}</td><td><span className={user.isActive ? 'tag success' : 'tag'}>{user.isActive ? 'Active' : 'Pending approval'}</span></td><td>{user.isActive ? <button className="secondary-button compact" onClick={() => approve(user.userId, false)}><X size={14} />Suspend</button> : <button className="primary-button compact" onClick={() => approve(user.userId, true)}><Check size={14} />Approve</button>}</td></tr>)}</tbody></table></div>}{showCreate && <div className="modal-backdrop"><form className="create-modal" onSubmit={createUser}><div className="panel-heading"><div><span className="panel-label">Admin provisioning</span><h3>Create user</h3></div><button type="button" className="icon-button" onClick={() => setShowCreate(false)}>×</button></div><label className="admin-field">Full name<input required value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })} /></label><label className="admin-field">Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="admin-field">Phone<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label className="admin-field">Temporary password<input required minLength="8" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><label className="admin-field">Role<select value={form.roleId} onChange={(event) => { const roleId = Number(event.target.value); const roleName = event.target.selectedOptions[0].text; setForm({ ...form, roleId, roleName }); }}><option value="2">Manager</option><option value="3">InventoryManager</option><option value="4">Accountant</option><option value="5">SalesPerson</option></select></label><button className="primary-button" type="submit">Create active user</button></form></div>}</div>;
};

export default AdminPage;
