import React, { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import api from '../lib/api';

const OperationsPage = () => {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const response = await api.get('/api/v1/dashboards/operations'); setData(response.data?.data || response.data || {}); setError(''); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const cards = data?.kpiCards || {};
  const items = [['pendingPurchases', 'Pending purchases'], ['pendingGoodsReceipt', 'Goods receipt'], ['currentInventory', 'Current inventory'], ['pendingOrders', 'Pending orders'], ['pendingDispatch', 'Pending dispatch'], ['returns', 'Returns'], ['damagedStock', 'Damaged stock']];
  return <div><div className="page-heading"><div><p className="eyebrow">Operations / daily flow</p><h2>Operations pulse</h2><p className="muted">Find the friction before it reaches a customer.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={16} />Refresh</button></div>{error && <div className="notice error">{error}</div>}{loading ? <div className="loading-state">Loading operations data...</div> : <><div className="kpi-grid">{items.map(([key, label]) => <article className="kpi-card" key={key}><span>{label}</span><strong>{Number(cards[key] || 0).toLocaleString('en-IN')}</strong><small><AlertTriangle size={13} /> Live operational count</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><span className="panel-label">Needs attention</span><h3>Low stock</h3></div></div>{data?.lowStockProducts?.length ? <div className="simple-list">{data.lowStockProducts.map((item) => <div className="list-row" key={item.productId}><span><strong>{item.productName}</strong><small>Minimum threshold {item.minimumThreshold}</small></span><b>{item.currentStock} left</b></div>)}</div> : <div className="empty-state"><AlertTriangle size={28} /><p>No low-stock alerts from the API.</p></div>}</section><section className="panel"><div className="panel-heading"><div><span className="panel-label">Supplier obligations</span><h3>Pending payments</h3></div></div>{data?.pendingSupplierPayments?.length ? <div className="simple-list">{data.pendingSupplierPayments.map((item) => <div className="list-row" key={item.supplierId}><span><strong>{item.supplierName}</strong><small>Due {new Date(item.dueDate).toLocaleDateString('en-IN')}</small></span><b>{Number(item.pendingAmount || 0).toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</b></div>)}</div> : <div className="empty-state"><p>No supplier payments returned.</p></div>}</section></div></>}</div>;
};
export default OperationsPage;
