import React, { useEffect, useState } from 'react';
import { RefreshCw, Send } from 'lucide-react';
import api from '../lib/api';

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const ProfitDistributionPage = () => {
  const now = new Date();
  const [year, setYear] = useState(now.getFullYear()); const [month, setMonth] = useState(now.getMonth() + 1);
  const [rows, setRows] = useState([]); const [note, setNote] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); try { const response = await api.get('/api/v1/investors/profit-distributions', { params: { year, month } }); setRows(response.data?.data || response.data || []); setError(''); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [year, month]);
  const distribute = async () => { setLoading(true); setMessage(''); try { const response = await api.post('/api/v1/investors/profit-distributions', { year: Number(year), month: Number(month), notes: note || null }); setMessage(`Distributed to ${response.data?.data?.distributionCount || response.data?.distributionCount || 0} investors.`); await load(); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  return <div><div className="page-heading"><div><p className="eyebrow">Finance / investors</p><h2>Monthly profit distribution</h2><p className="muted">Review a period before distributing its positive net profit.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={16} />Refresh</button></div><section className="panel"><div className="form-grid"><label>Year<input type="number" value={year} onChange={(event) => setYear(event.target.value)} /></label><label>Month<input type="number" min="1" max="12" value={month} onChange={(event) => setMonth(event.target.value)} /></label><label>Notes<input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional note" /></label><button className="primary-button" onClick={distribute}><Send size={16} />Distribute profit</button></div></section>{error && <div className="notice error">{error}</div>}{message && <div className="notice success">{message}</div>}{loading ? <div className="loading-state">Loading distributions...</div> : <section className="panel"><div className="panel-heading"><div><span className="panel-label">{month}/{year}</span><h3>{rows.length} allocations</h3></div></div><div className="table-wrap"><table><thead><tr><th>Investor</th><th>Ownership</th><th>Profit amount</th><th>Distributed</th></tr></thead><tbody>{rows.map((row) => <tr key={row.distributionId}><td>{row.investorName}</td><td>{row.ownershipPercent}%</td><td><strong>{money(row.profitAmount)}</strong></td><td>{row.distributedDate ? new Date(row.distributedDate).toLocaleDateString() : 'Pending'}</td></tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state">No distribution has been recorded for this period.</div>}</div></section>}</div>;
};
export default ProfitDistributionPage;
